opt_in_rules: # some rules are only opt-in
  - empty_count
  - redundant_nil_coalescing
  - switch_case_on_newline
  - force_unwrapping
  - conditional_returns_on_newline
  - closure_spacing
  - implicitly_unwrapped_optional
  - missing_docs
  - valid_docs

included: # paths to include during linting. `--path` is ignored if present.
  - STLocationRequest

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Frameworks

disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
